name: Deploy Vue.js App to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the Node.js version your project requires

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug SSH Setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -x  # Enable debugging
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 145.223.77.186 >> ~/.ssh/known_hosts
          ls -la ~/.ssh
          cat ~/.ssh/known_hosts
          ssh -p 65002 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no u196611491@145.223.77.186 "echo 'SSH connection successful'"

      - name: Test SSH Connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -p 65002 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no u196611491@145.223.77.186 "echo 'SSH connection successful'"

      - name: Deploy to Hostinger via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 145.223.77.186 >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -p 65002 -i ~/.ssh/id_rsa" --delete ./dist/ u196611491@145.223.77.186:/home/u196611491/domains/anthonyallen.dev/public_html/
